# Generated by Django 2.2 on 2020-06-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20200514_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ejemplar',
            new_name='ejemplares',
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='localizacion',
            field=models.CharField(max_length=30),
        ),
    ]
