# Generated by Django 2.2 on 2020-06-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20200624_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='paginas',
            field=models.IntegerField(),
        ),
    ]
